[package]
name = "sniper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util = "0.3.30"
serde_json = "1.0.114"
tokio = "1.36.0"
tokio-tungstenite = "0.21.0"
url = "2.5.0"
